motd: "                      &sect;b[&sect;fCraft In Space&sect;b]                      &sect;bBuild Spaceships &sect;8| &sect;6Use advanced Weapons & Mining"
lore:
  - '&sect;bCraftIn.Space&sect;e brings a &sect;6new'
  - '&sect;eway to play minecraft with'
  - '&sect;enever-seen-before features'
  - '&sect;esuch as the &sect;dcustomizable'
  - '&sect;dspacecraft&sect;e, &sect;dcombat system&sect;e, &sect;dautomations'
  - '&sect;eand the unique building'
  - '&sect;esystem which &sect;cdoes not &sect;einvolve'
  - '&sect;edownloading resource packs.'
