CREATE TABLE `Towns` (
`TOWN_ID` int(12) NOT NULL AUTO_INCREMENT, 
`TOWN_NAME` varchar(11) NOT NULL, 
`TOWN_DESC` varchar(384) NOT NULL DEFAULT 'A new town. Do /town setdesc Description to change this text.', 
`TOWN_OWNER` int(12) NOT NULL, 
`TOWN_OPTIONS` bigint(20) NOT NULL, 
`TOWN_SPAWN_X` int(12) NOT NULL, 
`TOWN_SPAWN_Y` int(12) NOT NULL, 
`TOWN_SPAWN_Z` int(12) NOT NULL, 
`TOWN_SPAWN_PITCH` decimal(7,4) NOT NULL, 
`TOWN_SPAWN_YAW` decimal(7,4) NOT NULL, 
`TOWN_SPAWN_WORLD` varchar(64) NOT NULL, 
`TOWN_TAX_TYPE` bigint(20) NOT NULL, 
`TOWN_ABANDONED_SINCE` bigint(20) NOT NULL, 
`TOWN_BANK` bigint(20) NOT NULL, 
`TOWN_TAX_PERCENTAGE` bigint(20) NOT NULL, 
`TOWN_CHUNKS_AUTORESELL` int(12) NOT NULL DEFAULT -1,
UNIQUE KEY `TOWN_ID` (`TOWN_ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `Towns` ADD CONSTRAINT NoDoubleOwner UNIQUE (TOWN_OWNER);
ALTER TABLE `Towns` ADD CONSTRAINT NoSameName UNIQUE (TOWN_NAME);

CREATE TABLE `TownWarps` (
`TOWN_ID` int(12) NOT NULL, 
`TOWN_WARP_NAME` varchar(16) NOT NULL, 
`TOWN_WARP_X` int(12) NOT NULL, 
`TOWN_WARP_Y` int(12) NOT NULL, 
`TOWN_WARP_Z` int(12) NOT NULL, 
`TOWN_WARP_PITCH` decimal(7,4) NOT NULL, 
`TOWN_WARP_YAW` decimal(7,4) NOT NULL, 
`TOWN_WARP_WORLD` varchar(64) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `TownWarps` ADD CONSTRAINT UniqueWarp UNIQUE (TOWN_ID, TOWN_WARP_NAME);

CREATE TABLE `TownInventory` (
`TOWN_ID` int(12) NOT NULL, 
`TOWN_INVENTORY_BLOCK_AMOUNT` int(12) NOT NULL, 
`TOWN_INVENTORY_BLOCK` int(12) NOT NULL, 
`TOWN_INVENTORY_BLOCKDAMAGE` int(12) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `TownInventory` ADD CONSTRAINT UniqueStack UNIQUE (TOWN_ID, TOWN_INVENTORY_BLOCK);

CREATE TABLE `TownExiles` (
`TOWN_ID` int(12) NOT NULL, 
`USER_ID` int(12) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `TownExiles` ADD CONSTRAINT UniqueExile UNIQUE (TOWN_ID, USER_ID);

CREATE TABLE `Chunks` (
`CHUNK_ID` int(12) NOT NULL AUTO_INCREMENT, 
`TOWN_ID` int(12) NOT NULL, 
`CHUNK_OWNER` int(12) NOT NULL, 
`CHUNK_X` int(12) NOT NULL, 
`CHUNK_Z` int(12) NOT NULL, 
`CHUNK_WORLD` varchar(64) NOT NULL, 
`CHUNK_TYPE` bigint(20) NOT NULL, 
`CHUNK_SALE_PRICE` bigint(20) NOT NULL, 
`CHUNK_TERRAFORMING` boolean NOT NULL, 
`CHUNK_TERRAFORM_BLOCK` int(12) NOT NULL, 
`CHUNK_TERRAFORM_BLOCKDAMAGE` int(12) NOT NULL, 
`CHUNK_TERRAFORM_MAX_Y` int(12) NOT NULL, 
UNIQUE KEY `CHUNK_ID` (`CHUNK_ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `ChunkMembers` (
`CHUNK_ID` int(12) NOT NULL, 
`USER_ID` int(12) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `ChunkMembers` ADD CONSTRAINT UniqueMembers UNIQUE (CHUNK_ID, USER_ID);

CREATE TABLE `Users` (
`USER_ID` int(12) NOT NULL AUTO_INCREMENT, 
`TOWN_ID` int(12) NOT NULL, 
`TOWN_RANK_ID` int(12) NOT NULL, 
`USER_NAME` varchar(16) NOT NULL, 
`USER_SHIELD_LASTS_UNTIL` bigint(20) NOT NULL, 
`USER_UUID` varchar(64) NOT NULL, 
`USER_IN_TOWN_CHAT` BOOLEAN NOT NULL DEFAULT FALSE, 
UNIQUE KEY `USER_ID` (`USER_ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

ALTER TABLE `Users` ADD CONSTRAINT UniqueUUID UNIQUE (USER_UUID);