name: Clans
description: Clans plugin
author: LolDatSec (hy)
version: 1
main: io.github.loldatsec.mcplugs.clans.Main
commands:
  c:
    description: Clans command.
    usage: /<command> <opt>
  clan:
    description: Clans command.
    usage: /<command> <opt>
  clans:
    description: Clans command.
    usage: /<command> <opt>
  cw:
    description: Toggle clanwars.
    usage: /<command>